director_name: bosh
environment: production
deployment_name: productionbosh
network: production-bosh
instance_profile: production-bosh-profile
gateway_host: prometheus-production.service.cf.internal
gateway_deployment: ""
blobstore:
  server_side_encryption: "AES256"
