---
platform: linux

inputs:
- {name: bosh-config}
- {name: ca-cert-store}
- {name: terraform-yaml}

run:
  path: bosh-config/ci/update-cloud-config.sh

params:
  OPS_PATHS:
  BOSH_CA_CERT:
  BOSH_ENVIRONMENT:
  BOSH_CLIENT:
  BOSH_CLIENT_SECRET:
