---
platform: linux

inputs:
- {name: bosh-config}
- {name: ca-cert-store}
- {name: terraform-yaml}
- {name: terraform-yaml-development}
- {name: terraform-yaml-staging}
- {name: terraform-yaml-production}


run:
  path: bosh-config/ci/update-cloud-config-tooling.sh
