---
platform: linux

image_resource:
  type: registry-image
  source:
    aws_access_key_id: ((ecr_aws_key))
    aws_secret_access_key: ((ecr_aws_secret))
    repository: harden-concourse-task
    aws_region: us-gov-west-1
    semver_constraint: ">= 1.0.0"

inputs:
- {name: bosh-config}
- {name: ca-cert-store}
- {name: terraform-yaml}
- {name: terraform-yaml-development}

run:
  path: bosh-config/ci/update-cloud-config-tooling.sh

params:
  OPS_PATHS:
  BOSH_CA_CERT:
  BOSH_ENVIRONMENT:
  BOSH_CLIENT:
  BOSH_CLIENT_SECRET:
