---
platform: linux

image_resource:
  type: registry-image
  source:
    aws_access_key_id: ((ecr_aws_key))
    aws_secret_access_key: ((ecr_aws_secret))
    repository: harden-concourse-task
    aws_region: us-gov-west-1
    tag: ((harden-concourse-task-tag))

inputs:
- {name: bosh-config}
- {name: bosh-deployment}
- {name: certificate}
- {name: terraform-yaml}
- {name: cg-s3-fisma-release, path: releases/fisma}
- {name: cg-s3-fisma-jammy-release, path: releases/fisma-jammy}
- {name: aide-release, path: releases/aide}
- {name: cg-s3-awslogs-bionic-release, path: releases/awslogs-bionic}
- {name: cg-s3-awslogs-jammy-release, path: releases/awslogs-jammy}
- {name: cg-s3-nessus-agent-release, path: releases/nessus-agent}
- {name: cg-s3-clamav-release, path: releases/clamav}
- {name: cg-s3-snort-release, path: releases/snort}
- {name: cg-s3-jammy-snort-release, path: releases/jammy-snort}
- {name: node-exporter-release, path: releases/node-exporter}
- {name: syslog-release, path: releases/syslog}

run:
  path: bosh-config/ci/update-runtime-config.sh

params:
  BOSH_CA_CERT:
  BOSH_ENVIRONMENT:
  BOSH_CLIENT:
  BOSH_CLIENT_SECRET:
  BOSH_ENV_NAME:
